#zuul:
#  routes:
#    path: /my-service/**
#    serviceId: mytestclient
   
#eureka:
#  client:
#    enabled: false
#    serviceUrl:
#      defaultZone: http://localhost:8761
spring:
  application:
    name: Zuul